# Generated by Django 5.1.5 on 2025-06-30 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
